const data = {
    info: {
        desc: "Linkis 团队由成员和贡献者组成。 成员可以直接访问 Linkis 项目的源代码并积极开发代码库。 贡献者通过提交补丁和向成员提供建议来改进项目。 项目的贡献者数量不限。 非常感谢对 Linkis 的所有贡献，无论是琐碎的修改或清理、重大的新特性新功能，还是其他的物质奖励。<br>如果你想参与贡献，可以直接去<a class=\"link\" href=\"https://github.com/apache/incubator-linkis\" target=\"_blank\" rel=\"noopener noreferrer\" >Apache Linkis</a> 并fork."
    },
    list: [
        {
            "name": "邸帅",
            "avatarUrl": "https://avatars.githubusercontent.com/u/11204592?s=60&v=4",
            "githubId": "sargentti",
            "gitUrl": "https://github.com/sargentti",
            "apacheId": "",
            "email": "shuaidi1024@gmail.com",
        },
        {
            "name": "尹强",
            "avatarUrl": "https://avatars.githubusercontent.com/u/13635442?s=60&v=4",
            "githubId": "wushengyeyouya",
            "gitUrl": "https://github.com/wushengyeyouya",
            "apacheId": "",
            "email": "enjoyyin91@gmail.com",
        },
        {
            "name": "王和平",
            "avatarUrl": "https://avatars.githubusercontent.com/u/11496700?s=60&v=4",
            "githubId": "peacewong",
            "gitUrl": "https://github.com/peacewong",
            "apacheId": "",
            "email": "wpeace1212@gmail.com",
        },
        {
            "name": "杨永坤",
            "avatarUrl": "https://avatars.githubusercontent.com/u/11203920?s=60&v=4",
            "githubId": "Alexkun",
            "gitUrl": "https://github.com/Alexkun",
            "apacheId": "",
            "email": "wimkunkun@gmail.com",
        },
        {
            "name": "杨峙岳",
            "avatarUrl": "https://avatars.githubusercontent.com/u/26363549?s=60&v=4",
            "githubId": "yangzhiyue",
            "gitUrl": "https://github.com/yangzhiyue",
            "apacheId": "",
            "email": "zjyzy19920513@gmail.com",
        },
        {
            "name": "刘有",
            "avatarUrl": "https://avatars.githubusercontent.com/u/12731931?s=60&v=4",
            "githubId": "liuyou2",
            "gitUrl": "https://github.com/liuyou2",
            "apacheId": "",
            "email": "liuyou181020@gmail.com",
        },
        {
            "name": "华德义",
            "avatarUrl": "https://avatars.githubusercontent.com/u/13026864?s=60&v=4",
            "githubId": "Davidhua1996",
            "gitUrl": "https://github.com/Davidhua1996",
            "apacheId": "",
            "email": "david_hua1996@gmail.com",
        },
        {
            "name": "白乐",
            "avatarUrl": "https://avatars.githubusercontent.com/u/13026864?s=60&v=4",
            "githubId": "leeebai",
            "gitUrl": "https://github.com/leeebai",
            "apacheId": "",
            "email": "blgg931026@gmail.com",
        },
        {
            "name": "王小刚",
            "avatarUrl": "https://avatars.githubusercontent.com/u/39912100?s=60&v=4",
            "githubId": "?",
            "gitUrl": "https://github.com/?",
            "apacheId": "",
            "email": "Adamyuanyuan@gmail.com",
        },
        {
            "name": "Hui Zhu",
            "avatarUrl": "https://avatars.githubusercontent.com/u/39912100?s=60&v=4",
            "githubId": "?",
            "gitUrl": "https://github.com/?",
            "apacheId": "",
            "email": "huashuizhuhui@gmail.com",
        },
        {
            "name": "Zhen Wang",
            "avatarUrl": "https://avatars.githubusercontent.com/u/39912100?s=60&v=4",
            "githubId": "?",
            "gitUrl": "https://github.com/?",
            "apacheId": "",
            "email": "wangzhen077@gmail.com",
        },
        {
            "name": "Rong Zhang",
            "avatarUrl": "https://avatars.githubusercontent.com/u/39478871?s=60&v=4",
            "githubId": "?",
            "gitUrl": "https://github.com/brianzhangrong",
            "apacheId": "",
            "email": "brian.rongzhang@gmail.com",
        },
        {
            "name": "Xiaohua Yi",
            "avatarUrl": "https://avatars.githubusercontent.com/u/39478871?s=60&v=4",
            "githubId": "?",
            "gitUrl": "https://github.com/?",
            "apacheId": "",
            "email": "yixiaohuamax@gmail.com",
        },
        {
            "name": "周可",
            "avatarUrl": "https://avatars.githubusercontent.com/u/5548534?s=60&v=4",
            "githubId": "?",
            "gitUrl": "https://github.com/?",
            "apacheId": "",
            "email": "bleachzk@gmail.com",
        },

        {
            "name": "谢建",
            "avatarUrl": "https://avatars.githubusercontent.com/u/5548534?s=60&v=4",
            "githubId": "?",
            "gitUrl": "https://github.com/?",
            "apacheId": "",
            "email": "Jackyxxie@gmail.com",
        }
    ]
}

export default data
