const data = {
    info: {
        desc: "The Linkis team is comprised of Members and Contributors. Members have direct access to the source of Linkis project and actively evolve the code-base. Contributors improve the project through submission of patches and suggestions to the Members. The number of Contributors to the project is unbounded. All contributions to Linkis are greatly appreciated, whether for trivial cleanups, big new features or other material rewards.<br>If you want to contribute, you can go directly to the <a class=\"link\" href=\"https://github.com/apache/incubator-linkis/\" target=\"_blank\" rel=\"noopener noreferrer\">Apache Linkis</a> and fork it."
    },
    list: [
        {
            "name": "Shuai Di",
            "avatarUrl": "https://avatars.githubusercontent.com/u/11204592?s=60&v=4",
            "githubId": "sargentti",
            "gitUrl": "https://github.com/sargentti",
            "apacheId": "",
            "email": "shuaidi1024@gmail.com",
        },
        {
            "name": "Qiang Yin",
            "avatarUrl": "https://avatars.githubusercontent.com/u/13635442?s=60&v=4",
            "githubId": "wushengyeyouya",
            "gitUrl": "https://github.com/wushengyeyouya",
            "apacheId": "",
            "email": "enjoyyin91@gmail.com",
        },
        {
            "name": "Heping Wang",
            "avatarUrl": "https://avatars.githubusercontent.com/u/11496700?s=60&v=4",
            "githubId": "peacewong",
            "gitUrl": "https://github.com/peacewong",
            "apacheId": "",
            "email": "wpeace1212@gmail.com",
        },
        {
            "name": "Yongkun Yang",
            "avatarUrl": "https://avatars.githubusercontent.com/u/11203920?s=60&v=4",
            "githubId": "Alexkun",
            "gitUrl": "https://github.com/Alexkun",
            "apacheId": "",
            "email": "wimkunkun@gmail.com",
        },
        {
            "name": "Zhiyue Yang",
            "avatarUrl": "https://avatars.githubusercontent.com/u/26363549?s=60&v=4",
            "githubId": "yangzhiyue",
            "gitUrl": "https://github.com/yangzhiyue",
            "apacheId": "",
            "email": "zjyzy19920513@gmail.com",
        },
        {
            "name": "You Liu",
            "avatarUrl": "https://avatars.githubusercontent.com/u/12731931?s=60&v=4",
            "githubId": "liuyou2",
            "gitUrl": "https://github.com/liuyou2",
            "apacheId": "",
            "email": "liuyou181020@gmail.com",
        },
        {
            "name": "Deyi Hua",
            "avatarUrl": "https://avatars.githubusercontent.com/u/13026864?s=60&v=4",
            "githubId": "Davidhua1996",
            "gitUrl": "https://github.com/Davidhua1996",
            "apacheId": "",
            "email": "david_hua1996@gmail.com",
        },
        {
            "name": "Le Bai",
            "avatarUrl": "https://avatars.githubusercontent.com/u/13026864?s=60&v=4",
            "githubId": "leeebai",
            "gitUrl": "https://github.com/leeebai",
            "apacheId": "",
            "email": "blgg931026@gmail.com",
        },
        {
            "name": "Xiaogang Wang",
            "avatarUrl": "https://avatars.githubusercontent.com/u/39912100?s=60&v=4",
            "githubId": "?",
            "gitUrl": "https://github.com/?",
            "apacheId": "",
            "email": "Adamyuanyuan@gmail.com",
        },
        {
            "name": "Hui Zhu",
            "avatarUrl": "https://avatars.githubusercontent.com/u/39912100?s=60&v=4",
            "githubId": "?",
            "gitUrl": "https://github.com/?",
            "apacheId": "",
            "email": "huashuizhuhui@gmail.com",
        },
        {
            "name": "Zhen Wang",
            "avatarUrl": "https://avatars.githubusercontent.com/u/39912100?s=60&v=4",
            "githubId": "?",
            "gitUrl": "https://github.com/?",
            "apacheId": "",
            "email": "wangzhen077@gmail.com",
        },
        {
            "name": "Rong Zhang",
            "avatarUrl": "https://avatars.githubusercontent.com/u/39478871?s=60&v=4",
            "githubId": "?",
            "gitUrl": "https://github.com/brianzhangrong",
            "apacheId": "",
            "email": "brian.rongzhang@gmail.com",
        },
        {
            "name": "Xiaohua Yi",
            "avatarUrl": "https://avatars.githubusercontent.com/u/39478871?s=60&v=4",
            "githubId": "?",
            "gitUrl": "https://github.com/?",
            "apacheId": "",
            "email": "yixiaohuamax@gmail.com",
        },
        {
            "name": "Ke Zhou",
            "avatarUrl": "https://avatars.githubusercontent.com/u/5548534?s=60&v=4",
            "githubId": "?",
            "gitUrl": "https://github.com/?",
            "apacheId": "",
            "email": "bleachzk@gmail.com",
        },

        {
            "name": "Jian Xie",
            "avatarUrl": "https://avatars.githubusercontent.com/u/5548534?s=60&v=4",
            "githubId": "?",
            "gitUrl": "https://github.com/?",
            "apacheId": "",
            "email": "Jackyxxie@gmail.com",
        }
    ]
}

export default data
