const data = [
    {
        "auther": "liangqilang ",
        "company": "Directly hired by Boss",
        "location": "Beijing, China",
        "contact": "zhuhui@kanzhun.com",
        "business scenario": "As a data middleware standard version service platform",
        "公司": "Boss直聘",
        "地点": "中国北京",
        "联系方式": "zhuhui@kanzhun.com",
        "业务场景": "作为数据中间件标准版服务平台",
    },
    {
        "auther": "zhanghaicheng1 ",
        "company": "Aisino",
        "location": "Hefei,China",
        "contact": "ah.zhanghaicheng@aisino.com",
        "business scenario": "Replace IQL products",
        "公司": "Aisino",
        "地点": "中国合肥",
        "联系方式": "ah.zhanghaicheng@aisino.com",
        "业务场景": "替代IQL产品"
    },
    {
        "auther": "JavaMrYang ",
        "company": "Beijing Lianchuang Zhirong",
        "location": "Changsha Hunan",
        "contact": "liu_yang@uisftech.com",
        "business scenario": "Provide support for big data service platform",
        "公司": "北京联创智融",
        "地点": "湖南长沙",
        "联系方式": "liu_yang@uisftech.com",
        "业务场景": "为大数据服务平台提供支持",

    },
    {
        "auther": "1245053895 ",
        "company": "Intelligent Manufacturing and Industrial Big Data Research Center of Xidian University",
        "location": "Xi'an, Shaanxi",
        "contact": "109738503@qq.com",
        "business scenario": "As a standard version of data middleware.",
        "公司": "西安电子科技大学智能制造与工业大数据研究中心",
        "地点": "陕西西安",
        "联系方式": "109738503@qq.com",
        "业务场景": "作为数据中间件标准版。",
    },
    {
        "auther": "RustRw ",
        "company": "Yitu Technology",
        "location": "Shanghai",
        "contact": "fei.xu2@yitu-inc.com",
        "business scenario": "unified data development platform,under investigation.",
        "公司": "依图科技",
        "地点": "上海",
        "联系方式": "fei.xu2@yitu-inc.com",
        "业务场景": " 统一数据开发平台, 调研中."
    },
    {
        "auther": "thinkborm ",
        "company": "g7 Internet of Things",
        "location": "Chengdu",
        "contact": "bigdata@g7.com.cn",
        "business scenario": "As a workbench for data developers and analysts.",
        "公司": "g7物联网",
        "地点": " 成都",
        "联系方式": " bigdata@g7.com.cn",
        "业务场景": " 作为数据开发人员、分析人员的工作台。",

    },
    {
        "auther": "sMallFAt6 ",
        "company": "National High Performance Computing Center of Huazhong University of Science and Technology",
        "location": "Wuhan",
        "contact": "2374007549@qq.com",
        "business scenario": "used to build a big data analysis platform",
        "公司": "华中科技大学国家高性能计算中心",
        "地点": " 武汉",
        "联系方式": " 2374007549@qq.com",
        "业务场景": " 用于搭建大数据分析平台",


    },
    {
        "auther": "ZengZeHua ",
        "company": "National High Performance Computing Center of Huazhong University of Science and Technology",
        "location": "Wuhan",
        "contact": "1979057506@qq.com",
        "business scenario": "used to build a big data analysis platform",
        "公司": "华中科技大学国家高性能计算中心",
        "地点": " 武汉",
        "联系方式": "1979057506@qq.com",
        "业务场景": " 用于搭建大数据分析平台",
    },
    {
        "auther": "liuzhimindluter ",
        "company": "China Sports Lottery Technology",
        "location": "Beijing",
        "contact": "252513499@qq.com",
        "business scenario": "Hope to achieve a more friendly multi-tenant development scenario",
        "公司": "中体彩科技",
        "地点": "北京",
        "联系方式": "252513499@qq.com",
        "业务场景": "希望实现更友好的多租户开发场景",
    },
    {
        "auther": "lkhuang ",
        "company": "Vanke Acquisition and Construction",
        "location": "Shenzhen",
        "contact": "kithlk@163.com",
        "business scenario": "unified data analysis platform testing and use;",
        "公司": "万科采筑",
        "地点": "深圳",
        "联系方式": "kithlk@163.com",
        "业务场景": " 统一数据分析平台,测试使用中",
    },
    {
        "auther": "yunhao2wei ",
        "company": "iquanwai",
        "location": "Shanghai",
        "contact": "yunhao2wei@163.com",
        "business scenario": "as a workbench for data analysts and BI personnel",
        "公司": "圈外同学",
        "地点": "上海",
        "联系方式": "yunhao2wei@163.com",
        "业务场景": "作为数据分析人员、BI人员的工作台",


    },
    {
        "auther": "felixlin47 ",
        "company": "Fujian Apex Software Co.Ltd.",
        "location": "Fuzhou",
        "contact": "76603008@qq.com",
        "business scenario": "Big data application scheduling platform under investigation...",
        "公司": "顶点软件",
        "地点": "福州",
        "联系方式": "76603008@qq.com",
        "业务场景": "大数据应用调度平台,调研中...",
    },
    {
        "auther": "cyofeiyue ",
        "company": "Nanjing Leading Technology /T3 Travel",
        "location": "Nanjing",
        "contact": "372003348@qq.com",
        "business scenario": "big data analysis query middleware research",
        "公司": "南京领行科技/T3出行",
        "地点": "南京",
        "联系方式": "372003348@qq.com",
        "业务场景": "大数据分析查询中间件调研",


    },
    {
        "auther": "feiyizhang ",
        "company": "Beijing Red Elephant Yunteng",
        "location": "Beijing",
        "contact": "95320534@qq.com",
        "business scenario": "Banking business solution research",
        "公司": "北京红象云腾",
        "地点": "北京",
        "联系方式": "953201534@qq.com",
        "业务场景": "银行业务解决方案调研",


    },
    {
        "auther": "Just-do-it-Fan ",
        "company": "Wah Lala",
        "location": "Beijing",
        "contact": "876103537@qq.com",
        "business scenario": "middleware of big data unified query platform",
        "公司": "哗啦啦",
        "地点": "北京",
        "联系方式": "876103537@qq.com",
        "业务场景": "大数据统一查询平台中间件",


    },
    {
        "auther": "weipengffk ",
        "company": "Lichuang Mall",
        "location": "Shenzhen China",
        "contact": "1310503090@qq.com",
        "business Scenario": "Research on Data Center Program",
        "公司": "立创商城",
        "地点": "中国深圳",
        "联系方式": "1310503090@qq.com",
        "业务场景": "数据中台方案调研",


    },
    {
        "auther": "wangshu-zhouyunfan ",
        "company": "Shu Select Cloud",
        "location": "Hangzhou",
        "contact": "18045173406@163.com",
        "business scenario": "external technical output of the data center",
        "公司": "数择云",
        "地点": "杭州",
        "联系方式": "18045173406@163.com",
        "业务场景": "数据中台对外技术输出",


    },
    {
        "auther": "robinzyx ",
        "company": "CLP Wanwei",
        "location": "Lanzhou",
        "contact": "18152063386@189.com",
        "business scenario": "data-centered government affairs  medical and other industry solutions",
        "公司": "中电万维",
        "地点": "兰州",
        "联系方式": "18152063386@189.com",
        "业务场景": "数据中台政务、医疗等行业解决方案",
    },
    {
        "auther": "77954309 ",
        "company": "Knowing Wisdom",
        "location": "Beijing",
        "contact": "77954309@qq.com",
        "business scenario": "data center construction of computing engine, various middle station services.",
        "公司": "知因智慧",
        "地点": "北京",
        "联系方式": "77954309@qq.com",
        "业务场景": "数据中台，构建计算引擎，各种中台服务。"


    },
    {
        "auther": "tgh-621 ",
        "company": "Chengdu Big Data Industry Research Institute",
        "location": "Chengdu",
        "contact": "93403464@qq.com",
        "business scenario": "data center",
        "公司": "成都大数据产业研究院",
        "地点": "成都",
        "联系方式": "93403464@qq.com",
        "业务场景": "数据中台",


    },
    {
        "auther": "zhihui-ge ",
        "company": "Hangzhou Electric Soul Network",
        "location": "Hangzhou",
        "contact": "2972333955@qq.com",
        "business scenario": "used to build a big data analysis platform",
        "公司": "杭州电魂网络",
        "地点": "杭州",
        "联系方式": "2972333955@qq.com",
        "业务场景": "用于搭建大数据分析平台",


    },
    {
        "auther": "chagsheg ",
        "company": "Beiming Digital",
        "location": "Guangzhou",
        "contact": "1420952288@qq.com",
        "business scenario": "data center",
        "公司": "北明数科",
        "地点": "广州",
        "联系方式": "1420952288@qq.com",
        "业务场景": "数据中台",


    },
    {
        "auther": "zhugekaoyu ",
        "company": "Zhongtong Yuncang",
        "location": "Hangzhou",
        "contact": "1756801194@qq.com",
        "business scenario": "research is used to replace CDH",
        "公司": "中通云仓",
        "地点": "杭州",
        "联系方式": "1756801194@qq.com",
        "业务场景": "调研用于替代CDH",


    },
    {
        "auther": "YxiangJ ",
        "company": "Dico",
        "location": "Zhengzhou",
        "contact": "284953505@qq.com",
        "business scenario": "data center",
        "公司": "迪科",
        "地点": "郑州",
        "联系方式": "284953505@qq.com",
        "业务场景": "数据中台",


    },
    {
        "auther": "zhangchao930216 ",
        "company": "Ping An Medical Insurance Technology",
        "location": "Shanghai",
        "contact": "790076723@qq.com",
        "business scenario": "data center",
        "公司": "平安医保科技",
        "地点": "上海",
        "联系方式": "790076723@qq.com",
        "业务场景": "数据中台",


    },
    {
        "auther": "xccoder ",
        "company": "Hikvision",
        "location": "Hangzhou China",
        "contact": "1843107737@qq.com",
        "business scenario": "Based on powerful data middleware to build a data development scenario for the Internet of Things industry.",
        "公司": "海康威视",
        "地点": "中国杭州",
        "联系方式": "1843107737@qq.com",
        "业务场景": "基于强大的数据中间件构建物联网行业的数据开发场景。",


    },
    {
        "auther": "ynlxc ",
        "company": "Orange Staging",
        "location": "Beijing China",
        "contact": "yndxx@qq.com",
        "business scenario": "build a company data center",
        "公司": "桔子分期",
        "地点": "中国北京",
        "联系方式": "yndxx@qq.com",
        "业务场景": "搭建公司数据中台",
    },
    {
        "auther": "chenxi0599 ",
        "company": "Guangzhou Yunxun Technology",
        "location": "Guangzhou  China",
        "contact": "179695222@qq.com",
        "business scenario": "Data Marketing Data Middle Office-Data R&D Platform",
        "公司": "广州云徙科技",
        "地点": "中国广州",
        "联系方式": "179695222@qq.com",
        "业务场景": "数据营销数据中台-数据研发平台",


    },
    {
        "auther": "liumingning ",
        "company": "In-laws Network",
        "location": "Beijing China",
        "contact": "547761853@qq.com",
        "business scenario": "the connector between the data base component and the user interaction component.",
        "公司": "亲家网络",
        "地点": "中国北京",
        "联系方式": "547761853@qq.com",
        "业务场景": "数据基础组件与用户交互组件之间的连接器。",


    },
    {
        "auther": "caoerbiao ",
        "company": "CLP Big Data Research Institute",
        "location": "Guiyang",
        "contact": "540765772@qq.com",
        "business scenario": "big data service platform data center",
        "公司": "中电科大数据研究院",
        "地点": "贵阳",
        "联系方式": "540765772@qq.com",
        "业务场景": "大数据服务平台数据中台"


    },
    {
        "auther": "Wzhipeng ",
        "company": "fordeal",
        "location": "Guangzhou China",
        "contact": "476855740@qq.com",
        "business scenario": "Connectors between data foundation components and user interaction components",
        "公司": "fordeal",
        "地点": "中国广州",
        "联系方式": "476855740@qq.com",
        "业务场景": "数据基础组件与用户交互组件之间的连接器",


    },
    {
        "auther": "swt88 ",
        "company": "Red Elephant Yunteng",
        "location": "Beijing China",
        "contact": "634995025@qq.com",
        "business scenario": "In order to achieve a good multi-tenancy",
        "公司": "红象云腾",
        "地点": "中国北京",
        "联系方式": "634995025@qq.com",
        "业务场景": "为了能很好的实现多租户",


    },
    {
        "auther": "itwhat126 ",
        "company": "Nanjing Austrian Information Industry Co.Ltd.",
        "location": "Nanjing",
        "contact": "819398357@qq.com",
        "business scenario": "research on company data middle-office solutions",
        "公司": "南京奥派信息产业股份公司",
        "地点": "南京",
        "联系方式": "819398357@qq.com",
        "业务场景": "公司数据中台解决方案调研",


    },
    {
        "auther": "Jesseszhang ",
        "company": "Ping An Property& Casualty",
        "location": "Shenzhen China",
        "contact": "1355077450@qq.com",
        "business scenario": "one-stop data platform solution research",
        "公司": "平安产险",
        "地点": "中国深圳",
        "联系方式": "1355077450@qq.com",
        "业务场景": "一站式数据平台解决方案调研",
    },
    {
        "auther": "Wf675721680 ",
        "company": "Baiwangyun",
        "location": "Beijing",
        "contact": "wufei@baiwang.com",
        "business scenario": "data governance",
        "公司": "百望云",
        "地点": "北京",
        "联系方式": "wufei@baiwang.com",
        "业务场景": "数据治理",
    },
    {
        "auther": "Adamyuanyuan ",
        "company": "China Telecom",
        "location": "Shanghai /Beijing, etc.",
        "contact": "913546481@qq.com",
        "business scenario": "one-stop data platform solution research",
        "公司": "中国电信",
        "地点": "上海/北京等",
        "联系方式": "913546481@qq.com",
        "业务场景": "一站式数据平台解决方案调研"
    },
    {
        "auther": "brianzhangrong ",
        "company": "Aijia Life",
        "location": "Jiangsu/Nanjing",
        "contact": "693404752@qq.com",
        "business scenario": "data center",
        "公司": "艾佳生活",
        "地点": "江苏/南京",
        "联系方式": "693404752@qq.com",
        "业务场景": "数据中台",
    },
    {
        "auther": "NicholasHua ",
        "company": "Nanjing Aokan Technology Co.Ltd.",
        "location": "Jiangsu/Nanjing",
        "contact": "774664386@qq.com",
        "business Scenario": "Research on Data Center Program",
        "公司": "南京奥看科技有限公司",
        "地点": "江苏/南京",
        "联系方式": "774664386@qq.com",
        "业务场景": "数据中台方案调研",


    },
    {
        "auther": "Tandoy ",
        "company": "Credit Life (Guangzhou) Intelligent Technology Co., Ltd.",
        "location": "Guangdong Guangzhou",
        "contact": "tangzhi@wecreditlife.com",
        "business scenario": "Data-centered financial industry solutions are in daily development and use.",
        "公司": "信用生活(广州)智能科技有限公司",
        "地点": "广东/广州",
        "联系方式": "tangzhi@wecreditlife.com",
        "业务场景": "数据中台金融行业解决方案，日常开发使用中。",
    },
    {
        "auther": "jacktao007 ",
        "company": "Zhongtong Service Public Information Co.Ltd.",
        "location": "Xinjiang/Urumqi",
        "contact": "7956214@qq.com",
        "business Scenario": "Research on Data Center Program",
        "公司": "中通服公众信息股份有限公司",
        "地点": "新疆/乌鲁木齐",
        "联系方式": "7956214@qq.com",
        "业务场景": "数据中台方案调研",


    },
    {
        "auther": "dddyszy ",
        "company": "Mobtech",
        "location": "Shanghai China",
        "contact": "shizhouyi123@gmail.com",
        "business scenario": "One-stop data development platform",
        "公司": "Mobtech",
        "地点": "中国上海",
        "联系方式": "shizhouyi123@gmail.com",
        "业务场景": "一站式数据开发平台",
    },
    {
        "auther": "zhangxhmuye ",
        "company": "Zhijiang Laboratory",
        "location": "Hangzhou China",
        "contact": "905896929@qq.com",
        "business scenario": "build a company data center and provide a one-stop development platform for data development",
        "公司": "之江实验室",
        "地点": "中国杭州",
        "联系方式": "905896929@qq.com",
        "业务场景": "搭建公司数据中台，向数据开发提供一站式开发平台",

    },
    {
        "auther": "lichuang22 ",
        "company": "Dongfangtong",
        "location": "Wuhan",
        "method": "1429883071@qq.com",
        "business Scenario": "Research on Data Center Program",
        "公司": "东方通",
        "地点": "武汉",
        "方式": "1429883071@qq.com",
        "业务场景": "数据中台方案调研",


    },
    {
        "auther": "nlallen ",
        "company": "Ideal Car",
        "location": "Beijing",
        "contact": "244495101@qq.com",
        "business scenario": "Build the company's big data platform as the underlying computing governance engine",
        "公司": "理想汽车",
        "地点": "北京",
        "联系方式": "244495101@qq.com",
        "业务场景": "搭建公司大数据平台，作为底层计算治理引擎",
    },
    {
        "auther": "linweijiang ",
        "company": "Twenty-six Degrees Digital Technology (Guangzhou) Co., Ltd.",
        "location": "Guangdong/Guangzhou",
        "contact": "linweijiang@26dudt.com",
        "business scenario": "One-stop data development platform (financial industry)",
        "公司": "二十六度数字科技（广州）有限公司",
        "地点": "广东/广州",
        "联系方式": "linweijiang@26dudt.com",
        "业务场景": "一站式数据开发平台（金融行业）",


    },
    {
        "auther": "emerkfu ",
        "company": "Shanghai Hemudu Industrial Development Co.Ltd.",
        "location": "Shanghai",
        "contact": "fushuai@homedo.com",
        "business scenario": "One-stop big data development platform",
        "公司": "上海河姆渡实业发展有限公司",
        "地点": "上海",
        "联系方式": "fushuai@homedo.com",
        "业务场景": "一站式大数据开发平台",


    },
    {
        "auther": "wyx94 ",
        "company": "Zhaolian Consumer Finance Co. Ltd.",
        "location": "Shenzhen",
        "contact": "wangyuxing@mucfc.com",
        "business scenario": "build the company's big data platform as the underlying computing engine",
        "公司": "招联消费金融有限公司",
        "地点": "深圳",
        "联系方式": "wangyuxing@mucfc.com",
        "业务场景": "搭建公司大数据平台，作为底层计算引擎"
    },
    {
        "auther": "saLeox ",
        "company": "Sea Limited",
        "location": "Singapore",
        "contact": "sunshun18@126.com",
        "business scenario": "Investigate the middleware for big data platform.",
        "公司": "冬海集团",
        "地点": "新加坡",
        "联系方式": "sunshun18@126.com",
        "业务场景": "调用大数据平台的中间件"
    }
]
