const  img=[
    {"url":"邮政银行.jpg"},
    {"url":"中国民生银行.jpg"},
    {"url":"美团点评.jpg"},
    {"url":"中国电信.png"},
    {"url":"交通银行.jpg"},
    {"url":"招商银行.jpg"},
    {"url":"招联消费金融有限公司.png"},
    {"url":"平安.png"},
    // {"url":"平安医保科技.png"},
    {"url":"360.png"},
    {"url":"海康威视.png"},
    {"url":"理想汽车.png"},
    {"url":"百信银行.jpg"},
    {"url":"百望云.png"},
    {"url":"立创商城.png"},
    {"url":"红象云腾.png"},
    {"url":"腾讯财经.jpg"},
    {"url":"艾佳生活.jpg"},
    // {"url":"萨摩耶云.png"},
    {"url":"蔚来汽车.jpg"},
    {"url":"顶点软件.png"},
    {"url":"97wulian.png"},
    // {"url":"T3出行.png"},
    {"url":"aisino.png"},
    {"url":"boss.png"},
    {"url":"huazhong.jpg"},
    {"url":"lianchuang.png"},
    // {"url":"mobtech..png"},
    {"url":"xidian.jpg"},
    {"url":"yitu.png"},
    {"url":"zhongticaipng.png"},
    {"url":"万科采筑.png"},
    {"url":"东方通.png"},
    {"url":"中国电科.jpg"},
    {"url":"中通云仓.png"},
    // {"url":"中通服公众信息股份有限公司.png"},
    // {"url":"之江实验室.png"},
    {"url":"云图科技.png"},
    {"url":"京东数科.jpg"},
    {"url":"信用生活.png"},
    {"url":"哗啦啦.jpg"},
    {"url":"圈外同学.png"},
    {"url":"天翼云.png"},
    {"url":"广州云徙科技.png"},
    // {"url":"成都大数据.png"},
    {"url":"杭州电魂网络.png"},
    {"url":"桔子分期.png"}
]
export default img
