const  img=[
    //===not exit in "who is using linkis issue"
    // {"url":"邮政银行.jpg"},
    // {"url":"中国民生银行.jpg"},
    // {"url":"美团点评.jpg"},
    //天翼云{"url":"中国电信.png"},
    // {"url":"交通银行.jpg"},
    // {"url":"招商银行.jpg"},
    // {"url":"平安医保科技.png"},
    //* {"url":"百信银行.jpg"},
    //* {"url":"腾讯财经.jpg"},
    //* {"url":"京东数科.jpg"},
    {"url":"招联消费金融有限公司.png"},
    {"url":"平安.png"},
    {"url":"荣耀.png"},
    {"url":"360.png"},
    {"url":"天翼云.png"},
    {"url":"理想汽车.png"},
    {"url":"萨摩耶云.png"},
    {"url":"蔚来汽车.jpg"},
    {"url":"T3出行.png"},
    {"url":"百望云.png"},
    {"url":"海康威视.png"},
    {"url":"立创商城.png"},
    {"url":"红象云腾.png"},
    {"url":"艾佳生活.jpg"},
    {"url":"顶点软件.png"},
    {"url":"97物联.png"},
    {"url":"航天信息.png"},
    {"url":"boss直聘.png"},
    {"url":"华中科技大学.jpg"},
    {"url":"联创智融.png"},
    {"url":"mobtech.png"},
    {"url":"西安电子科技大学.jpg"},
    {"url":"依图.png"},
    {"url":"中体彩科技.png"},
    {"url":"万科采筑.png"},
    {"url":"东方通.png"},
    {"url":"中国电科.jpg"},
    {"url":"中通云仓.png"},
    {"url":"中国通信服务.png"},
    {"url":"之江实验室.png"},
    {"url":"信用生活.png"},
    {"url":"哗啦啦.jpg"},
    {"url":"圈外同学.png"},
    {"url":"云徒科技.png"},
    {"url":"成都大数据.png"},
    {"url":"杭州电魂网络.png"},
    {"url":"桔子分期.png"}
]
export default img
