name: Build and Deploy to Netlify

on:
  push:
    branches: [dev,dev-*]
  pull_request_target:
    branches: [dev,dev-*]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.3.4
        with:
          submodules: recursive
      - uses: actions/setup-node@v2.2.0
        with:
          node-version: 16

          
      - name: install
        run: |
          npm install
      - name: Build
        run: |
          npm run build
          cp .asf.yaml build
          cp .htaccess build
          cp doap.rdf build   

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: "./build"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "${{ github.event.pull_request.title }}, Deploy from GitHub Actions"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 10
