name: Check for sensitive data

on:
  pull_request:
    branches: [dev,dev-*]
  push:
    branches: [dev,dev-*]

jobs:
  detection:
    name: automatic-detection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.2.0
        with:
          node-version: 16

      - run: |
          ipis=`{ grep -rn "[1-9]\{2,3\}\.[0-9]\{2,3\}\.[0-9]\{1,3\}.[0-9]\{1,3\}" * --exclude=custom.scss || true;}`
          bdpujesis=`{ grep -rn "bdpujes" * || true;}`
          bdpdwsis=`{ grep -rn "bdpdws" * || true;}`
          if [[ -n "$ipis" ]];then echo "$ipis"; fi
          if [[ -n "$bdpujesis" ]];then echo "$bdpujesis"; fi
          if [[ -n "$bdpdwsis" ]];then echo "$bdpdwsis"; fi
          if [[ -n "$bdpdwsis" ]] || [[ -n "$ipis" ]] || [[ -n "$bdpujesis" ]];then echo "check error!" && exit 123; else echo "check success"; fi