name: Automatic Detection

on:
  pull_request:
    branches: [dev,dev-*]
  push:
    branches: [dev,dev-*]

jobs:
  detection:
    name: automatic-detection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.2.0
        with:
          node-version: 16

      - run: grep -rn "/([0,1]?\d{1,2}|2([0-4][0-9]|5[0-5]))(\.([0,1]?\d{1,2}|2([0-4][0-9]|5[0-5]))){3}/" *