name: Scheduled Merge

on:
  schedule:
    # Run everyday at 0:00 AM or 12:00 AM (See https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07)
    - cron: "0 0,12 * * *"

jobs:
  # The purpose of this workflow is to periodically merge "asf-staging" into "asf-site"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: 'asf-staging'
        
      - name: scheduled merge
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /home/runner/work/linkis-website/linkis-website/
          publish_branch: asf-site