name: Scheduled crawl

on:
  schedule:
    # Run everyday at 0:00 AM or 12:00 AM (See https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07)
    - cron: "0 0,12 * * *"

jobs:
  # The purpose of this workflow is to periodically merge "asf-staging" into "asf-site"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: 'dev'
      
      - name: scheduled crawl linkis website contributor
        uses: ./.github/actions/Contributor_crawler
        with:
          repo: apache/linkis-website
          num: 1000
      
      - name: scheduled crawl linkis contributor
        uses: ./.github/actions/Contributor_crawler
        with:
          repo: apache/linkis
          num: 1000
        
      - name: scheduled commit contributor 
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
